#!/bin/sh

usage() {
  CMD=`basename $0`
  echo "Usage: $CMD [POFILE]"
  echo "  If POFILE is not specified, ja/ja.po will be used."
  echo "  Note: This command must be executed in the $HELPDIR directory."
}

MODULE=`git remote -v | sed -n -e 's!^.*git.gnome.org.*/\([[:alnum:]+-]\{1,\}\) (fetch)$!\1!p' | head -n 1`
case "$MODULE" in
  gnome-user-docs)
    HELPDIR=gnome-help
    POT=gnome-help.pot
    ;;
  release-notes)
    HELPDIR=help
    POT=release-notes.pot
    ;;
  *)
    echo "Error: The module '${MODULE}' is unknown. It must be 'gnome-user-docs' or 'release-notes'."
    exit 1
    ;;
esac


OPT=`getopt h "$@"`
if [ $? -ne 0 ]; then
  usage >&2
  exit 1
fi
eval set -- "$OPT"
while :; do
  case "$1" in
    -h)
      usage
      exit 0
      ;;
    --)
      shift 1
      break
      ;;
    *)
      usage >&2
      exit 1
      ;;
  esac
done

DIR="`basename $PWD`"
if [ x"$DIR" != x"$HELPDIR" ]; then
  echo "Working directory is not ${HELPDIR}" >&2
  echo "" >&2
  usage >&2
  exit 1
fi

PO=$1
if [ x"$PO" = x ]; then
  PO=ja/ja.po
fi
if [ ! -f "$PO" ]; then
  echo "$PO: No such file" >&2
  echo "" >&2
  usage >&2
  exit 1
fi

if [ ! -f Makefile ]; then
  (
    cd ../
    ./autogen.sh -q >/dev/null
    if [ $? -ne 0 ]; then
      exit 1
    fi
  )
fi
make -s pot >/dev/null
if [ $? -ne 0 ]; then
  exit 1
fi

msgmerge --no-wrap --previous "$PO" "$POT"
